services:
  espocrm-db:
    image: mariadb:latest
    container_name: espocrm-db
    command: --max-allowed-packet=64MB
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    environment:
      MARIADB_ROOT_PASSWORD: $SERVICE_PASSWORD_MARIADBROOT
      MARIADB_DATABASE: espocrm
      MARIADB_USER: espocrm
      MARIADB_PASSWORD: $SERVICE_PASSWORD_MARIADB
    volumes:
      - ./espocrm-db:/var/lib/mysql

  espocrm:
    image: espocrm/espocrm:9-apache
    container_name: espocrm
    environment:
      ESPOCRM_DATABASE_HOST: espocrm-db
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: $SERVICE_PASSWORD_MARIADB
      ESPOCRM_ADMIN_USERNAME: $SERVICE_USER_ESPOADMINUSER
      ESPOCRM_ADMIN_PASSWORD: $SERVICE_PASSWORD_ESPOADMINPASSWORD
      ESPOCRM_SITE_URL: $SERVICE_FQDN_ESPOCRM
    restart: always
    depends_on:
      espocrm-db:
        condition: service_healthy
    volumes:
      - ./espocrm:/var/www/html
    labels:
      - traefik.enable=true                                           
      - traefik.http.routers.espocrm-app.rule=Host(`{$SERVICE_FQDN_ESPOCRM}`)
      - traefik.http.routers.espocrm-app.entrypoints=websecure
      - traefik.http.routers.espocrm-app.tls=true
      - traefik.http.routers.espocrm-app.tls.certresolver=esporesolver

  espocrm-daemon:
    image: espocrm/espocrm:latest
    container_name: espocrm-daemon
    volumes:
      - espocrm:/var/www/html
    restart: always
    entrypoint: docker-daemon.sh

  espocrm-websocket:
    image: espocrm/espocrm:latest
    container_name: espocrm-websocket
    environment:
     ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
     ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
     ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
    volumes:
      - espocrm:/var/www/html
    restart: always
    entrypoint: docker-websocket.sh
    labels:
      - traefik.enable=true
      - traefik.http.routers.espocrm-ws.rule=Host(`{SERVICE_FQDN_ESPOCRM}`) && PathPrefix(`/ws`)
      - traefik.http.routers.espocrm-ws.entrypoints=websecure
      - traefik.http.routers.espocrm-ws.tls=true
      - traefik.http.routers.espocrm-ws.tls.certresolver=esporesolver
      - traefik.http.services.espocrm-ws.loadbalancer.server.port=8080

volumes:
  espocrm-db:
  espocrm:
